/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-11-06 07:20:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1603711248665L));
    _jspx_dependants.put("jar:file:/C:/Users/Vinit/Desktop/Advanced%20Java/Spring/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/contactbook5/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fpassword_0026_005fplaceholder_005fpath_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005fpassword_0026_005fplaceholder_005fpath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody.release();
    _005fjspx_005ftagPool_005fspr_005fpassword_0026_005fplaceholder_005fpath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\" integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/login.css\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("    font-family: Tahoma,Geneva,sans-serif;\r\n");
      out.write("    color: white;\r\n");
      out.write("     background-image:linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/5.jpg');\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    height:100vh;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"signin\">\r\n");
      out.write("\t");
      //  spr:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_spr_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_spr_005fform_005f0_reused = false;
      try {
        _jspx_th_spr_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_spr_005fform_005f0.setParent(null);
        // /login_form.jsp(27,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spr_005fform_005f0.setAction("login.htm");
        // /login_form.jsp(27,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spr_005fform_005f0.setMethod("post");
        // /login_form.jsp(27,1) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_spr_005fform_005f0.setCommandName("user");
        int[] _jspx_push_body_count_spr_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_spr_005fform_005f0 = _jspx_th_spr_005fform_005f0.doStartTag();
          if (_jspx_eval_spr_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("            <h2 style=\"color: white\"><u>Login Here</u></h2>\r\n");
              out.write("            <br>\r\n");
              out.write("\r\n");
              out.write("           ");
              if (_jspx_meth_spr_005finput_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t<font color=\"red\" >");
              //  spr:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spr_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spr_005ferrors_005f0_reused = false;
              try {
                _jspx_th_spr_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_spr_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
                // /login_form.jsp(32,22) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spr_005ferrors_005f0.setPath("emailId");
                int[] _jspx_push_body_count_spr_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_spr_005ferrors_005f0 = _jspx_th_spr_005ferrors_005f0.doStartTag();
                  if (_jspx_th_spr_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spr_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spr_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spr_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spr_005ferrors_005f0);
                _jspx_th_spr_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005ferrors_005f0_reused);
              }
              out.write("</font>\r\n");
              out.write("           ");
              if (_jspx_meth_spr_005fpassword_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("           <font color=\"red\" >");
              //  spr:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_spr_005ferrors_005f1 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_spr_005ferrors_005f1_reused = false;
              try {
                _jspx_th_spr_005ferrors_005f1.setPageContext(_jspx_page_context);
                _jspx_th_spr_005ferrors_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
                // /login_form.jsp(34,30) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_spr_005ferrors_005f1.setPath("userPass");
                int[] _jspx_push_body_count_spr_005ferrors_005f1 = new int[] { 0 };
                try {
                  int _jspx_eval_spr_005ferrors_005f1 = _jspx_th_spr_005ferrors_005f1.doStartTag();
                  if (_jspx_th_spr_005ferrors_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_spr_005ferrors_005f1[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_spr_005ferrors_005f1.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_spr_005ferrors_005f1.doFinally();
                }
                _005fjspx_005ftagPool_005fspr_005ferrors_0026_005fpath_005fnobody.reuse(_jspx_th_spr_005ferrors_005f1);
                _jspx_th_spr_005ferrors_005f1_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005ferrors_005f1, _jsp_getInstanceManager(), _jspx_th_spr_005ferrors_005f1_reused);
              }
              out.write("</font>         \r\n");
              out.write("            <br><br>\r\n");
              out.write("           \r\n");
              out.write("            <a href=\"\"><input type=\"submit\"   value=\"Login\" class=\"btn btn-warning\"></a>\r\n");
              out.write("                    <br>\r\n");
              out.write("                    <div id=\"container\">\r\n");
              out.write("                <a href=\"forget_password.jsp\" >Forget Password</a>\r\n");
              out.write("            </div><br>\r\n");
              out.write("             <div class=\"col-md-12 text-center\">\r\n");
              out.write("                      \t<a href=\"prep_reg_form.htm\" class=\"btn btn-success\">SignIn</a>\r\n");
              out.write("\r\n");
              out.write("                        <a href=\"index.jsp\" class=\"btn btn-danger  \">Back</a> \r\n");
              out.write("                    </div>\r\n");
              out.write("\t\r\n");
              out.write("\t");
              int evalDoAfterBody = _jspx_th_spr_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_spr_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_spr_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_spr_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_spr_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.reuse(_jspx_th_spr_005fform_005f0);
        _jspx_th_spr_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spr_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f0_reused = false;
    try {
      _jspx_th_spr_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /login_form.jsp(31,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f0.setPath("emailId");
      // /login_form.jsp(31,11) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "placeholder", "Enter email");
      int[] _jspx_push_body_count_spr_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f0 = _jspx_th_spr_005finput_005f0.doStartTag();
        if (_jspx_th_spr_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_spr_005finput_005f0);
      _jspx_th_spr_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_spr_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fspr_005fpassword_0026_005fplaceholder_005fpath_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    boolean _jspx_th_spr_005fpassword_005f0_reused = false;
    try {
      _jspx_th_spr_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /login_form.jsp(33,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fpassword_005f0.setPath("userPass");
      // /login_form.jsp(33,11) null
      _jspx_th_spr_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "Enter Password");
      int[] _jspx_push_body_count_spr_005fpassword_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fpassword_005f0 = _jspx_th_spr_005fpassword_005f0.doStartTag();
        if (_jspx_th_spr_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fpassword_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fpassword_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fpassword_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fpassword_0026_005fplaceholder_005fpath_005fnobody.reuse(_jspx_th_spr_005fpassword_005f0);
      _jspx_th_spr_005fpassword_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fpassword_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fpassword_005f0_reused);
    }
    return false;
  }
}
